---
- name: install apt-transport-https
  apt: { name: apt-transport-https, install_recommends: no }
- name: add buildkite-agent apt key
  apt_key: { keyserver: keyserver.ubuntu.com, id: 32A37959C2FA5C3C99EFBC32A79206696452D198 }
- name: add buildkite-agent apt repo
  apt_repository: { repo: 'deb https://apt.buildkite.com/buildkite-agent stable main' }
- name: install buildkite-agent
  apt: { name: "buildkite-agent={{ agent_version }}-*", install_recommends: no, update_cache: yes, cache_valid_time: 3600 }
- name: configure buildkite agent
  lineinfile:
    dest: /etc/buildkite-agent/buildkite-agent.cfg
    regexp: "^(# )?{{ item.key }}="
    line: "{{ item.key }}={{item.value}}"
  with_dict:
    token: '"{{ buildkite_agent_token }}"'
    tags: "{{ agent_tags }}"
    priority: "{{ priority }}"
  notify: restart buildkite-agent
- name: add allowed-pipelines pre-checkout hook
  template:
    src: allowed-pipelines-pre-checkout.sh.j2
    dest: /etc/buildkite-agent/hooks/pre-checkout
    owner: buildkite-agent
    mode: 0700
  when: allowed_pipelines != None
- name: add empty checkout hook
  copy:
    src: empty-checkout.sh
    dest: /etc/buildkite-agent/hooks/checkout
    owner: buildkite-agent
    mode: 0700
  when: skip_checkout
- name: create systemd service drop-in
  file:
    dest: /etc/systemd/system/buildkite-agent.service.d
    state: directory
- name: create systemd service drop-in
  file:
    src: /etc/systemd/system/buildkite-agent.service.d
    dest: /etc/systemd/system/buildkite-agent@.service.d
    state: link
- name: increase TimeoutStopSec for buildkite agents
  copy:
    dest: /etc/systemd/system/buildkite-agent.service.d/timeout.conf
    # https://www.freedesktop.org/software/systemd/man/systemd.service.html#TimeoutStopSec=
    # https://www.freedesktop.org/software/systemd/man/systemd.kill.html#KillMode=
    content: |
      [Service]
      TimeoutStopSec={{ stop_timeout }}
      KillMode=mixed
  notify: systemctl daemon-reload

- name: disable buildkite-agent
  service: { name: buildkite-agent, enabled: no, state: stopped }
- name: enable buildkite-agents
  service: { name: "buildkite-agent@{{ item }}", enabled: yes, state: started }
  with_items: "{{ range(1, num_agents + 1) | list }}"

- include_tasks: agent_shutdown_check.yml
  when: inventory_hostname in groups.buildkite_demand_agents
