---
- name: setting hostname
  hostname: { name: "{{ inventory_hostname_short }}" }
- name: setting hostnames for IPs
  lineinfile:
    dest: /etc/hosts
    regexp: ^{{ item.ip | replace('.', '\.') }}
    line: "{{ item.ip }} {{ item.hostnames | join(' ') }}"
  with_items:
    - ip: 127.0.0.1
      hostnames: [localhost.localdomain, localhost]
    - ip: ::1
      hostnames: [localhost.localdomain, localhost]
    - ip: 127.0.1.1
      hostnames: ["{{ inventory_hostname }}", "{{ inventory_hostname_short }}"]
    - ip: "{{ ansible_default_ipv4.address }}"
      hostnames: ["{{ inventory_hostname }}", "{{ inventory_hostname_short }}"]
    - ip: "{{ ansible_default_ipv6.address }}"
      hostnames: ["{{ inventory_hostname }}", "{{ inventory_hostname_short }}"]
