---
- name: uninstall resolvconf
  apt: { name: resolvconf, state: absent }
- name: configure DNS servers
  lineinfile:
    dest: /etc/systemd/resolved.conf
    regexp: '^#?DNS='
    line: 'DNS=1.1.1.1 8.8.8.8 2606:4700:4700::1001'
  when: disable_resolved_tcp_stub
  notify: restart systemd-resolved
# seems to work with systemd 238 though
# (also see https://github.com/systemd/systemd/pull/4061)
- name: disable conflicting systemd-resolved tcp stub listener
  lineinfile:
    dest: /etc/systemd/resolved.conf
    regexp: '^#?DNSStubListener'
    line: 'DNSStubListener=udp'
  when: disable_resolved_tcp_stub
  notify: restart systemd-resolved
- name: enable systemd-resolved
  service: { name: systemd-resolved, enabled: yes, state: started }
  when: ansible_distribution_major_version >= 17
- name: symlink resolv.conf
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
