---
- name: restart postfix
  service: { name: postfix, state: restarted }
- name: restart systemd-journald
  service: { name: systemd-journald, state: restarted }
- name: restart sshd
  service: { name: sshd, state: restarted }
- name: newaliases
  command: newaliases
- name: netplan apply
  command: netplan apply
